// Copyright 2023 Jason Hazel (@jasonhazel)
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once
#define VIAL_KEYBOARD_UID {0xF7, 0x3A, 0x77, 0x47, 0x2F, 0xF8, 0x10, 0x42}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 4}
#define VIAL_UNLOCK_COMBO_COLS { 0, 0}

#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define DYNAMIC_KEYMAP_LAYER_COUNT 6